//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПР_9.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class test9EntitiesL : DbContext
    {
        private static test9EntitiesL _context;
        public test9EntitiesL()
            : base("name=test9EntitiesL")
        {
        }

        public static test9EntitiesL GetContext()
        {
            if (_context == null)
            {
                _context = new test9EntitiesL();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}

